import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const cldrVersion = "48.2";
const cldrTag = "release-48-2";
const sourceRoot = `https://raw.githubusercontent.com/unicode-org/cldr/${cldrTag}`;
const annotationUrl = `${sourceRoot}/common/annotations/de.xml`;
const emojiUrl = `${sourceRoot}/tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/emoji/emoji-test.txt`;
const includedGroups = new Set(["Animals & Nature", "Food & Drink", "Objects"]);

const [annotationResponse, emojiResponse] = await Promise.all([
  fetch(annotationUrl),
  fetch(emojiUrl),
]);
if (!annotationResponse.ok || !emojiResponse.ok) {
  throw new Error(
    `Unicode CLDR konnte nicht geladen werden (${annotationResponse.status}/${emojiResponse.status}).`,
  );
}

const emojiByComparableSequence = new Map<string, string>();
let currentGroup = "";
for (const line of (await emojiResponse.text()).split("\n")) {
  const group = line.match(/^# group: (.+)$/)?.[1];
  if (group) {
    currentGroup = group;
    continue;
  }
  if (!includedGroups.has(currentGroup)) {
    continue;
  }
  const emoji = line.match(/;\s*fully-qualified\s*#\s*(\S+)\s+E[\d.]+/)?.[1];
  if (emoji) {
    emojiByComparableSequence.set(comparableEmoji(emoji), emoji);
  }
}

const emojiNames = new Map<string, Set<string>>();
const annotationDocument = await annotationResponse.text();
for (const annotation of annotationDocument.matchAll(
  /<annotation\s+([^>]+)>([^<]*)<\/annotation>/g,
)) {
  const attributes = annotation[1] || "";
  if (!/\btype="tts"/.test(attributes)) {
    continue;
  }
  const codePoint = attributes.match(/\bcp="([^"]+)"/)?.[1];
  const rawName = annotation[2];
  if (!codePoint || !rawName) {
    continue;
  }
  const emoji = emojiByComparableSequence.get(comparableEmoji(decodeXml(codePoint)));
  if (!emoji) {
    continue;
  }
  const name = normalizeName(decodeXml(rawName));
  const matches = emojiNames.get(name) || new Set<string>();
  matches.add(emoji);
  emojiNames.set(name, matches);
}

const entries = [...emojiNames]
  .filter(([, emojis]) => emojis.size === 1)
  .map(([name, emojis]) => [name, [...emojis][0] || ""] as const)
  .sort(([left], [right]) => left.localeCompare(right, "de"));
const serializedEntries = entries
  .map(([name, emoji]) => `  [${JSON.stringify(name)}, ${JSON.stringify(emoji)}],`)
  .join("\n");
const generatedFile = `// Generated by scripts/generate-product-icons.ts from Unicode CLDR ${cldrVersion}.
// Source data: ${annotationUrl}
// Copyright © Unicode, Inc. SPDX-License-Identifier: Unicode-3.0.
// Do not edit this file manually; maintain product aliases in product-icons.ts.

export const unicodeProductIcons: Readonly<Record<string, string>> = Object.fromEntries([
${serializedEntries}
]);
`;

await writeFile(resolve("src/client/product-icons.generated.ts"), generatedFile);
console.info(`${entries.length} deutsche Unicode-Symbolnamen wurden erzeugt.`);

function comparableEmoji(value: string): string {
  return value.replaceAll("\uFE0F", "");
}

function normalizeName(value: string): string {
  return value.normalize("NFKC").trim().replace(/\s+/g, " ").toLocaleLowerCase("de-DE");
}

function decodeXml(value: string): string {
  return value
    .replaceAll("&amp;", "&")
    .replaceAll("&quot;", '"')
    .replaceAll("&apos;", "'")
    .replaceAll("&lt;", "<")
    .replaceAll("&gt;", ">");
}
